# Generated by Django 4.2.4 on 2023-08-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resource', models.CharField(max_length=255)),
                ('payload', models.TextField()),
                ('headers', models.TextField()),
                ('user_id', models.IntegerField()),
                ('http_method', models.CharField(max_length=10)),
                ('processing_time_ms', models.PositiveIntegerField()),
                ('client_http_status', models.PositiveIntegerField()),
                ('api_http_status', models.PositiveIntegerField()),
                ('client_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
